name: Test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  test-ci:
    name: Test - on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-2025' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rancher Desktop
        run: |
          ./helpful_tools/uninstall-docker-engine-for-wcow.ps1
          winget install --id jazzdelightsme.WingetPathUpdater --source winget
          winget install --id SUSE.RancherDesktop --source winget
          rdctl start --application.start-in-background --container-engine.name=moby --kubernetes.enabled=false
          ./helpful_tools/wait-for-rancher-desktop-backend.ps1
          "PATH=$env:PATH" >> $env:GITHUB_ENV
      - name: Test Rancher Desktop
        run: |
          docker context ls
          docker run hello-world:linux
